### ISSUE TITLE
can't convert Pathname into String

### ISSUE THREAD

**Issue by somebee** [wycats/bundler#93]
I cannot get the bundler (master-branch) to work at all..

$ gem bundle
ERROR:  While executing gem ... (TypeError)
    can't convert Pathname into String

0.6 works here.. The Gemspec is just a simple file with a single dependency.

**Comment by somebee** [comment]
Using ruby 1.9.1

**Comment by wycats** [comment]
Can you provide the full stack trace?

**Comment by somebee** [comment]
how? running it with verbose mode does not show anything more

**Comment by somebee** [comment]
$ gem bundle --backtrace
ERROR:  While executing gem ... (TypeError)
    can't convert Pathname into String
    /usr/local/ruby-1.9.1-p243/lib/ruby/gems/1.9.1/gems/bundler-0.7.0.pre/lib/bundler/dsl.rb:7:in `instance_eval'
    /usr/local/ruby-1.9.1-p243/lib/ruby/gems/1.9.1/gems/bundler-0.7.0.pre/lib/bundler/dsl.rb:7:in`evaluate'
    /usr/local/ruby-1.9.1-p243/lib/ruby/gems/1.9.1/gems/bundler-0.7.0.pre/lib/bundler/environment.rb:45:in `initialize'
    /usr/local/ruby-1.9.1-p243/lib/ruby/gems/1.9.1/gems/bundler-0.7.0.pre/lib/bundler/environment.rb:20:in`new'
    /usr/local/ruby-1.9.1-p243/lib/ruby/gems/1.9.1/gems/bundler-0.7.0.pre/lib/bundler/environment.rb:20:in `load'
    /usr/local/ruby-1.9.1-p243/lib/ruby/gems/1.9.1/gems/bundler-0.7.0.pre/lib/bundler/cli.rb:35:in`initialize'
    /usr/local/ruby-1.9.1-p243/lib/ruby/gems/1.9.1/gems/bundler-0.7.0.pre/lib/bundler/cli.rb:6:in `new'
    /usr/local/ruby-1.9.1-p243/lib/ruby/gems/1.9.1/gems/bundler-0.7.0.pre/lib/bundler/cli.rb:6:in`run'
    /usr/local/ruby-1.9.1-p243/lib/ruby/gems/1.9.1/gems/bundler-0.7.0.pre/lib/bundler/commands/bundle_command.rb:63:in `execute'
    /usr/local/ruby-1.9.1-p243/lib/ruby/gems/1.9.1/gems/rubygems-update-1.3.5/lib/rubygems/command.rb:257:in`invoke'
    /usr/local/ruby-1.9.1-p243/lib/ruby/gems/1.9.1/gems/rubygems-update-1.3.5/lib/rubygems/command_manager.rb:132:in `process_args'
    /usr/local/ruby-1.9.1-p243/lib/ruby/gems/1.9.1/gems/rubygems-update-1.3.5/lib/rubygems/command_manager.rb:102:in`run'
    /usr/local/ruby-1.9.1-p243/lib/ruby/gems/1.9.1/gems/rubygems-update-1.3.5/lib/rubygems/gem_runner.rb:58:in `run'
    /usr/local/ruby/bin/gem:24:in`<main>'

**Comment by somebee** [comment]
Fix: just convert the pathname there before sending it in...

7 # builder.instance_eval(File.read(file), file.to_s)
instead of # builder.instance_eval(File.read(file), file)

**Comment by carllerche** [comment]
This should be fixed on master

**Comment by mperham** [comment]
Still a problem on the latest:

/Users/mperham/.rvm/gems/jruby-1.5.6@banyan/gems/bundler-1.0.15/lib/bundler/source.rb:696:in `chdir': can't convert Pathname into String (TypeError)
    from /Users/mperham/.rvm/gems/jruby-1.5.6@banyan/gems/bundler-1.0.15/lib/bundler/source.rb:696:in`in_cache'
    from /Users/mperham/.rvm/gems/jruby-1.5.6@banyan/gems/bundler-1.0.15/lib/bundler/source.rb:670:in `has_revision_cached?'
    from /Users/mperham/.rvm/gems/jruby-1.5.6@banyan/gems/bundler-1.0.15/lib/bundler/source.rb:638:in`cache'
    from /Users/mperham/.rvm/gems/jruby-1.5.6@banyan/gems/bundler-1.0.15/lib/bundler/source.rb:544:in `specs'
    from /Users/mperham/.rvm/gems/jruby-1.5.6@banyan/gems/bundler-1.0.15/lib/bundler/definition.rb:147:in`resolve'
    from /Users/mperham/.rvm/gems/jruby-1.5.6@banyan/gems/bundler-1.0.15/lib/bundler/definition.rb:145:in `each'
    from /Users/mperham/.rvm/gems/jruby-1.5.6@banyan/gems/bundler-1.0.15/lib/bundler/definition.rb:145:in`resolve'
    from /Users/mperham/.rvm/gems/jruby-1.5.6@banyan/gems/bundler-1.0.15/lib/bundler/definition.rb:90:in `specs'
